#include<stdio.h>
main()
{
    int x,y;
    for(x=5;x>=1;x--)
    {
        for(y=1;y<=x;y++)
        {
            printf("%d",y);
        }
        printf("\n");
    }
     for(x=2;x<=5;x++)
    {
        for(y=1;y<=x;y++)
        {
            printf("%d",y);
        }
        printf("\n");
    }
}